version: 2
jobs:
  test:
    docker:
      - image: dlang2/dmd-circleci:2.089.0-beta.1

    environment:
      DC: dmd
    steps:
      - checkout
      - run:
          name: Test
          command: bash ./test.sh
workflows:
  version: 2
  test:
    jobs:
      - test
